name: Build

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: 
          - 'MSE_RBA'
          - 'MSE_BTC'

    runs-on: ubuntu-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
        
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        
    - name: Install Arduino CLI and Tools
      run: |
        pip3 install adafruit-nrfutil
        # make all our directories we need for files and libraries
        mkdir $HOME/.arduino15
        mkdir $HOME/.arduino15/packages
        mkdir $HOME/Arduino
        mkdir $HOME/Arduino/libraries
        curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
        echo $GITHUB_WORKSPACE/bin >> $GITHUB_PATH
        
    - name: Install BSP and Libraries
      env:
        BSP_URL: https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
        BSP_PATH: .arduino15/packages/adafruit/hardware/nrf52
      run: |
        arduino-cli config init
        arduino-cli core update-index
        arduino-cli core update-index --additional-urls $BSP_URL
        arduino-cli core install adafruit:nrf52 --additional-urls $BSP_URL

        # Replace release BSP with our code
        BSP_VERSION=`eval ls $HOME/$BSP_PATH`
        rm -r $HOME/$BSP_PATH/*
        ln -s $GITHUB_WORKSPACE $HOME/$BSP_PATH/$BSP_VERSION

        # Install library dependency - don't do most of this as we (mostly) don't care about library 
        # compatibility, we don't provide an I2C or SPI interface, nor do we have an onboard NeoPixel
        # see also many .MSE_RBA.test.skip files in library examples
        arduino-cli lib install "MIDI Library" "Adafruit GFX Library" "Adafruit NeoPixel"
        # arduino-cli lib install "Adafruit AHRS" "Adafruit APDS9960 Library" "Adafruit Arcada Library" "Adafruit BMP280 Library" "Adafruit Circuit Playground" "Adafruit EPD" "Adafruit HX8357 Library" "Adafruit ILI9341" "Adafruit LIS3MDL" "Adafruit LSM6DS" "Adafruit NeoMatrix" "Adafruit Sensor Calibration" "Adafruit SHT31 Library" "Adafruit SSD1306" "Adafruit ST7735 and ST7789 Library" "SdFat - Adafruit Fork"
        # arduino-cli lib install "Arduino_TensorFlowLite"
        
        # TODO use firmata master to prevent build error with gcc v9 (should be remove after 2.5.9 is released)
        # https://github.com/firmata/arduino/pull/438
        git clone --depth 1 https://github.com/firmata/arduino.git $HOME/Arduino/libraries/firmata

        # TODO temporarily remove TinyUSB pre-1.0.0 version install by arduino-cli
        # this fails gracefully if the folder doesn't exist
        rm -rf $HOME/Arduino/libraries/Adafruit_TinyUSB_Library

        # Library summary
        arduino-cli lib list

        # create skip files in here as we want to make merging this with future updates
        # from Adafruit easier than manually creating / merging files
        # also allows us to skip examples within submodules (e.g. Adafruit_TinyUSB_Arduino)
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/Composite/mouse_external_flash/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/HID/hid_composite/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/HID/hid_composite_joy_featherwing/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/MassStorage/msc_external_flash/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/MassStorage/msc_external_flash_sdcard/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/MassStorage/msc_sd/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/MassStorage/msc_sdfat/.MSE_RBA.test.skip        
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Adafruit_TinyUSB_Arduino/examples/WebUSB/webusb_rgb/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Hardware/adc_vbat/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Peripheral/ancs_oled/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Peripheral/client_cts_oled/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Peripheral/image_eink_transfer/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Peripheral/image_transfer/.MSE_RBA.test.skip 
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Peripheral/neomatrix/.MSE_RBA.test.skip                
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Bluefruit52Lib/examples/Peripheral/StandardFirmataBLE/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/SPI/examples/BarometricPressureSensor/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/SPI/examples/DigitalPotControl/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/digital_potentiometer/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/main_reader/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/main_scan/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/main_writer/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/secondary_receiver/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/secondary_sender/.MSE_RBA.test.skip
        touch $HOME/work/MSE_nRF52_Arduino/MSE_nRF52_Arduino/libraries/Wire/examples/SFRRanger_reader/.MSE_RBA.test.skip

    - name: Build examples
      run: python3 tools/build_all.py ${{ matrix.arduino-platform }}
